spring:
  application:
    name: "Connection API Service"
  neo4j:
    authentication:
      username: ${NEO4J_AUTH_USERNAME:neo4j}
      password: ${NEO4J_AUTH_PASSWORD:password}
    uri: ${NEO4J_URI:bolt://localhost:7687}

management:
  health:
    neo4j:
      enabled: true